name: yugioh_api_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.5
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/